#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

if ! which go > /dev/null; then
	echo "go not found"
	exit 1
fi

outdir="$PWD/_output/bin"
mkdir -p ${outdir} || true


if [ ! -z ${GOINSTALL+x} ] && [ "${GOINSTALL}" = "y" ]
then
	GOBIN=$outdir CGO_ENABLED=0 go install -installsuffix cgo
else
	CGO_ENABLED=0 go build -installsuffix cgo -o ${outdir}/kenc
fi

if [ ! -z ${BUILDCONTAINER+x} ] &&  [ "$BUILDCONTAINER" == "y" ]
then
  docker build -t $IMAGE -f ./hack/deploy/Dockerfile .
  docker push $IMAGE
fi
